//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niacomsoft.Disco.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niacomsoft.Disco.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 错误的资源名称 “@resourceName”。 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_wrong_resource_name {
            get {
                return ResourceManager.GetString("ArgumentException_wrong_resource_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的编码 “@encoding”。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullException_null_encoding {
            get {
                return ResourceManager.GetString("ArgumentNullException_null_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的路径字符串。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullException_null_path_string {
            get {
                return ResourceManager.GetString("ArgumentNullException_null_path_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接串不允许为空。 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringOptions_invalid_connection_string {
            get {
                return ResourceManager.GetString("ConnectionStringOptions_invalid_connection_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接串名称 “Name” 不允许为空。 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringOptions_invalid_name {
            get {
                return ResourceManager.GetString("ConnectionStringOptions_invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}小时前 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_a_few_hours_ago {
            get {
                return ResourceManager.GetString("DateExtensions_a_few_hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}分钟前 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_a_few_minutes_ago {
            get {
                return ResourceManager.GetString("DateExtensions_a_few_minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}天前 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_few_days_ago {
            get {
                return ResourceManager.GetString("DateExtensions_few_days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_full_date {
            get {
                return ResourceManager.GetString("DateExtensions_full_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刚刚 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_just_now {
            get {
                return ResourceManager.GetString("DateExtensions_just_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HH:mm 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_same_day {
            get {
                return ResourceManager.GetString("DateExtensions_same_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MM月dd日 的本地化字符串。
        /// </summary>
        internal static string DateExtensions_same_year {
            get {
                return ResourceManager.GetString("DateExtensions_same_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分布式配置服务邮件通知 - {0} 的本地化字符串。
        /// </summary>
        internal static string EmailNotificationOptions_default_subject_template {
            get {
                return ResourceManager.GetString("EmailNotificationOptions_default_subject_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “Disco” 抛出了一个未处理的运行时异常。 的本地化字符串。
        /// </summary>
        internal static string Exception_default_message {
            get {
                return ResourceManager.GetString("Exception_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当 {0} 时，引发了一个 “{1}” 类型的异常：{2} 的本地化字符串。
        /// </summary>
        internal static string ExceptionExtensions_get_logging_message {
            get {
                return ResourceManager.GetString("ExceptionExtensions_get_logging_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用方法 “{0}:{1}” 的本地化字符串。
        /// </summary>
        internal static string ExceptionExtensions_get_logging_message_no_cause_reason {
            get {
                return ResourceManager.GetString("ExceptionExtensions_get_logging_message_no_cause_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将 “{0}” 类型转换成 “{1}” 类型值。 的本地化字符串。
        /// </summary>
        internal static string InvalidCastException_default_message {
            get {
                return ResourceManager.GetString("InvalidCastException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的网络通信端口号数值范围。 的本地化字符串。
        /// </summary>
        internal static string NetworkCommunicationPort_invalid_port_number_range {
            get {
                return ResourceManager.GetString("NetworkCommunicationPort_invalid_port_number_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的密钥长度。 的本地化字符串。
        /// </summary>
        internal static string SecretKey_invalid_length {
            get {
                return ResourceManager.GetString("SecretKey_invalid_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分布式配置管理服务 Disco 的本地化字符串。
        /// </summary>
        internal static string SmtpSenderOptions_friendly_name {
            get {
                return ResourceManager.GetString("SmtpSenderOptions_friendly_name", resourceCulture);
            }
        }
    }
}
